### ISSUE TITLE
cannot compile with ghc-8

### ISSUE THREAD

**Issue by jwaldmann** [amcphail/hmatrix-gsl-stats#12]
with ghc-8.0.1, I am seeing a lot of errors like this one:
```
Preprocessing library hmatrix-gsl-stats-0.4.1.3...
[ 1 of 10] Compiling Numeric.GSL.Fitting.Linear ( lib/Numeric/GSL/Fitting/Linear.hs, dist/build/Numeric/GSL/Fitting/Linear.o )

lib/Numeric/GSL/Fitting/Linear.hs:65:51: error:
    • Couldn't match expected type ‘IO CInt’
                  with actual type ‘TransRaw
                                      (TransRaw
                                         (CInt -> Ptr Double -> CInt -> Ptr Double -> IO CInt) b1
                                       -> IO r1)
                                      b0
                                    -> IO r0’
    • Probable cause: ‘(#)’ is applied to too few arguments
      In the first argument of ‘(#|)’, namely
        ‘(fitting_linear c0 c1 chi_sq cov00 cov01 cov11) # x # y’
```
this is with hmatrix-0.18.0.0. It works with hmatrix-0.17.0.2, so I suggest to put this exact version bound in the cabal file, as a temporary fix.

**Comment by amcphail** [comment]
Hi,

Thanks for the email.  It looks like there's an operator from hmatrix that
has changed definitions.

I'm in the middle of exams.  I'll have a look in a week or so.

Vivian

**Comment by amcphail** [comment]
I've added an upper bound as suggested temporarily.

**Comment by amcphail** [comment]
Update for new definition of `apply` and `applyRaw` from hmatrix 0.18
